### ISSUE TITLE
fstitch bidir failing when segment file is empty

### ISSUE THREAD

**Issue by magruca** [Dowell-Lab/FStitch#15]
Need to have a bug fix for this and a clear error thrown when the segment file is empty. This happens normally if the data needed to be flipped and therefore FStitch segment/train occurs on the wrong strand.

Command error:
  /Users/magr0763/.local/lib/python3.6/site-packages/bidir/bidir.py:67: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
    fstitch_seg_file = pd.read_table((args.fstitch_seg_filename), header=None, skiprows=1, usecols=range(6))
  Traceback (most recent call last):
    File "/Users/magr0763/.local/bin/bidir", line 11, in <module>
      load_entry_point('FStitch-Bidir==0.2.2', 'console_scripts', 'bidir')()
    File "/Users/magr0763/.local/lib/python3.6/site-packages/bidir/__init__.py", line 4, in bidir
      bd.main()
    File "/Users/magr0763/.local/lib/python3.6/site-packages/bidir/bidir.py", line 67, in main
      fstitch_seg_file = pd.read_table((args.fstitch_seg_filename), header=None, skiprows=1, usecols=range(6))
    File "/Users/magr0763/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 702, in parser_f
      return _read(filepath_or_buffer, kwds)
    File "/Users/magr0763/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 429, in _read
      parser = TextFileReader(filepath_or_buffer, **kwds)
    File "/Users/magr0763/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 895, in __init__
      self._make_engine(self.engine)
    File "/Users/magr0763/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
      self._engine = CParserWrapper(self.f, **self.options)
    File "/Users/magr0763/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1853, in __init__
      self._reader = parsers.TextReader(src, **kwds)
    File "pandas/_libs/parsers.pyx", line 545, in pandas._libs.parsers.TextReader.__cinit__
  pandas.errors.EmptyDataError: No columns to parse from file

**Comment by magruca** [comment]
added value error to catch this
